title = "NCM Inc. Hotel Renovation"
baseURL = "https://ncmreno.netlify.app/"

languageCode = "en-us"
DefaultContentLanguage = "en"
paginate = 10

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Gabriel Higginbotham"
  github = "https://github.com/higginbg"
  og_image = "/img/logos/logo.png"
  sitename = "NCM Inc"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
